### ISSUE TITLE
Fails to run with Golang 1.6+

### ISSUE THREAD

**Issue by weingart** [GeertJohan/go.hid#14]
Unfortunately, this fails to run with the latest Golang:

> panic: runtime error: cgo argument has Go pointer to Go pointer
> 
> goroutine 1 [running]:
> panic(0x4100900, 0xc82005c270)
>   /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
> github.com/GeertJohan/cgo%2ewchar.convertWcharStringToGoString(0xc82007c100, 0xa, 0x10, 0x0, 0x0, 0x0, 0x0)
>   /Users/weingart/src/github.com/GeertJohan/cgo.wchar/convert.go:150 +0x521
> github.com/GeertJohan/cgo%2ewchar.WcharStringPtrToGoString(0x4309800, 0x0, 0x0, 0x0, 0x0)
>   /Users/weingart/src/github.com/GeertJohan/cgo.wchar/wchar.go:141 +0x91
> github.com/GeertJohan/go%2ehid.Enumerate(0xc800000000, 0x0, 0x0, 0x0, 0x0, 0x0)
>   /Users/weingart/src/github.com/GeertJohan/go.hid/hid.go:211 +0x3e6
# sadface

**Comment by eduncan911** [comment]
Go 1.6 changed the rules for passing pointers:

https://golang.org/cmd/cgo/#hdr-Passing_pointers

**Comment by eduncan911** [comment]
Some tips on what changed with 1.6, and the new rules:

https://talks.golang.org/2016/state-of-go.slide#44

**Comment by eduncan911** [comment]
Looks like error pasted above points to this line of code:

https://github.com/GeertJohan/cgo.wchar/blob/c95658974985df55ea7a6a09984b2b2393c7a80f/wchar.go#L141

According to the new specs, you can't return a structure with an embedded pointer.

After a brief look at the code, `WcharString` is a slice of `[]Wchar`.

```
// go representation of a wchar string (array)
type WcharString []Wchar
```

Maybe it's because the fact that slices are passed by ref/pointers in Go?  Perhaps that's the error?

Arrays in Go, on the other hand, are passed by Value.  Perhaps the fix is for `WcharString` to return an array of `Wchar` instead?

`Wchar` is either an int16 or int32 depending on the platform according to code, which are value objects so they should be fine.

Since you can't dynamically allocate an array in Go (must be a fixed constant size when defined), you may have to look at the underlying C hid code to see what buffer size it can accept - and change the code to pass in a buffer amount of [#]Wchar instead of the slice of []Wchar.


---

Alternatively, one might just have two versions of Go on their system (Go1.5 for example) and use go 1.5 to compile this library for now if it is never resolved.

You can run multiple versions of Go on your system.  I do it by using a symlink to the current/live version I want to use and switch the symlink to older versions to compile test projects.  For example, my "installation directory" looks like:

```
$ ls -l ~/.go/
current -> go1.6
go1.4.3
go1.5.3
go1.6
```

You'll note that my `~/.go/current/` is a symlink to `~/.go/go1.6`.  This is my `$GOROOT` env variable.  Yes, I know, not supposed to set GOROOT - unless you are, well, doing exactly this!  It works perfectly, if you set it up right.

Also take special note that I use a special hidden directory prefixed with a DOT, `/.go/`, to store my installations.  This separates my `~/go/src/*` project files (never install Go into your GOPATH!!!)

In my `Makefile` (build scripts) of my projects, if I want to change Go runtime versions, I usually setup an environment var of what I want to run for the `Makefile`.  Like:

```
GO16BRANCH=`ln -sfn ~/.go/go1.6 ~/.go/current`
GO15BRANCH=`ln -sfn ~/.go/go1.5.3 ~/.go/current`
GO14BRANCH=`ln -sfn ~/.go/go1.4.3 ~/.go/current`
```

That way, in my `Makefile`, I have developers eval the variable - if they have custom Go installs.  If they do not, and no var is set, no big deal. 

```
eval "${GO15BRANCH}"
```

Just may have to do this for now to get this to build and continue.

**Comment by weingart** [comment]
I understand that there are differences between cgo from 1.5 to 1.6, hence this bug report.  :)

**Comment by arvenil** [comment]
soooo... it still doesn't work with go 1.6+?

**Comment by karalabe** [comment]
I created an alternative version of this library, self-cotnained, go-gettable. Should work on all Go versions. Feel free to take a look https://github.com/karalabe/hid :)

**Comment by GeertJohan** [comment]
Sorry for not being active here. I'll update the README to point new users to [karalabe/hid](https://github.com/karalabe/hid), which I think is a great improvement. Thanks @karalabe!
It doesn't support all the function calls yet, but I'm sure those can be added when needed. In any case the setup is a lot nicer and it works cross-platform and with newer versions of Go.
